name: Graphql Schema Check
 
on: [push]
 
jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
 
    steps:
      - uses: actions/checkout@v6

      - name: debug refs
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "github.sha=${{ github.sha }}"

          git ls-remote origin ref/pull/1/merge

      - uses: graphql-hive/graphql-inspector@master
        with:
          schema: 'develop:apps/backend/schema.gql'
          # annotations: false

